### ISSUE TITLE
Clarify fish completion install

### ISSUE THREAD

**Issue by ariebovenberg** [streammachineio/cli#41]
Nice setup. A small thing I encountered. The instructions to install completions for the `fish` shell seem outdated. (`source "strm/path.fish.inc"`)

There seems to be a `strm completion fish` command so it seems you already have something better in mind :)

**Comment by trietsch** [comment]
Hey @ariebovenberg, thanks for reporting! We'll take a look at this. If you find out the solution to setup `fish` autocomplete, please let us know.

**Comment by ariebovenberg** [comment]
@trietsch looks like you're already mostly there.

this does the trick
```
strm completion fish > ~/.config/fish/completions/strm.fish
```

Documentation on distributing fish completions: https://fishshell.com/docs/current/completions.html
example homebrew formula distributing completions: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/poetry.rb

**Comment by trietsch** [comment]
Nice, thanks for sharing! We'll update the caveats section of our Homebrew formula. Regarding the `poetry.rb` example formula for installing autocomplete automatically, if I recall correctly, I have attempted that. But I'll definitely try that again, now that I've got another example :)

**Comment by trietsch** [comment]
Fixed in https://github.com/streammachineio/cli/releases/tag/v1.6.0
